### ISSUE TITLE
[Implement sniff] Disallow advertising/tracking codes

### ISSUE THREAD

**Issue by grappler** [WPTRT/WordPress-Coding-Standards#125]
#### Rule type:
Error

#### Rule:

Advertising/tracking codes in both PHP as well as JS and CSS and any other potential files which contain this type of code. Google search code `cx=[0-9]{21}:[a-z0-9]{10}` and Google advertising code `pub-[0-9]{16}`

#### Theme check file covering this rule:
https://github.com/WordPress/theme-check/blob/master/checks/badthings.php

#### To do:
- [ ] Add the rule in the Theme Review handbook to the **_Requirements_** page.
- [ ] Create unit tests
- [ ] Create new sniff

**Comment by kkoppenhaver** [comment]
@grappler If no one is tackling this already, I can take a look at this one.

**Comment by grappler** [comment]
@kkoppenhaver That would be great! No one is working on this yet.

**Comment by carolinan** [comment]
@kkoppenhaver Maybe you can work with and improve branch 125 :).   https://github.com/WPTRT/WordPress-Coding-Standards/blob/feature/issue-125-google-search-and-ad-codes/WordPress/Sniffs/Theme/NoAdvertisingOrTrackingSniff.php

**Comment by kkoppenhaver** [comment]
@carolinan Thanks for the heads up on that! I'll take a look.

**Comment by dingo-d** [comment]
@kkoppenhaver Hi! Any news on this sniff?
