### ISSUE TITLE
De-fork from WPCS

### ISSUE THREAD

**Issue by jrfnl** [WPTRT/WordPress-Coding-Standards#169]
Follow-on issue for #163.

Action list:
- [ ] Get approval for PR #26 and merge it.
- [ ] Review if any of the other open PRs are _nearly_ ready, if so, fix them up, get approval and merge them.
- [ ] Decide about ruleset name and repo name - see #167. 
- [ ] Decide about sniff categories - see #166.
- [ ] Contact GH about getting the repo decoupled.
- [ ] Change the repo name and adjust Packagist if needed.
- [ ] Create a PR for the decoupling against `develop`.
- [ ] Once the PR is merged, open a PR to merge `develop` into `master` and tag release `0.1.0`.
- [ ] Change the default PR branch of this repo to `develop` and remove the `theme-review-sniffs` branch.
- [ ] Change the PR branch of all open PRs to `develop` and add a comment in the PR that the PR needs to be adjusted for the new categories.

**Comment by jrfnl** [comment]
FYI: The detaching of this repo from the WPCS repo in git terms is happening soon.

There are/were 18 forks of the WPCS repo which were based off the TRTCS fork. Those forks will remain attached to this repository and will not revert to being forks of WPCS upstream.

Once the detaching is done, the repo name will be updated as well to make it abundantly clear that this repo is a stand-alone project from that point on-wards.

* Forks of this repo may want to follow suite and rename their fork to match the new repo name `WPThemeReview`.
* If you contribute to both WPCS as well as to this repo, you will need to make a new fork of WPCS.
* To continue contributing to this repo, no other action is needed, aside from keeping your fork up to date with the state of this repo - which will soon change drastically -. :sunglasses: 

/cc @carolinan @djrmom @dmtrmrv @ernilambar @Roshanb54 @fervillz @fklein-lu @khacoder @kkoppenhaver @krishna19 @miya0001 @nasabikram @Pross @purevtsooj @RCSWebDev @rinkuyadav999 @sachyya @selul

**Comment by jrfnl** [comment]
>  Create a PR for the decoupling against develop.

For the decoupling, there are two possible ways to go:
1. Use the WPCS base as is, remove everything we don't need, adjust the things we do.
    This will keep the history intact, but that also means that this repo will have seven years of (irrelevant) WPCS history and the contributors list etc will be heavily skewed towards WPCS contributors.
    I imagine, this will make the threshold to start contributing to this repo higher for new contributors as everything done for this repo before the split will be quite obfuscated.
2. Start clean.
    What I mean by that is: Deleting the current `master` and `develop` branches and creating new virgin orphan branches with those same names. Creating an orphan feature branch, cherrypicking all the commits done for this project + the files from WPCS which we want to keep and adjust. And then pulling the branch with all the cherrypicks to the empty `develop` branch.
    This would clear out all the old WPCS history - except for the history of the files we are keeping (should be only +/- 8 files) - and give us a clean history with only the commits relevant to this repository and credit to the people who have contributed to the files which will stay in the repository.
    The downside of this is, that it may be confusing for existing contributors that the repo will have changed completely.

The effect of either option on existing pull request is about the same. In both cases, the pull requests will need to be rebased against the new `develop` anyway and the sniff categories changed, As the open PRs are all either new sniffs - and therefore new files - or changes against files which were new to this repo anyway, the rebase should be relatively painless either way.

@pattonwebz @dingo-d What do you think ? Have you got a preference ?

Option 1 is the simplest to execute, option 2 would give us a far cleaner base to continue from.

**Comment by dingo-d** [comment]
As discussed on slack, I'm for option 2

**Comment by jrfnl** [comment]
The branch which is intended to be the new repo content & history, is now online for review: https://github.com/WPTRT/WPThemeReview/tree/feature/163-166-167-169-decouple-from-WPCS

**Comment by dingo-d** [comment]
This has been done, so ti can be closed, no?

**Comment by jrfnl** [comment]
I think we left it open at the time as the open PRs which got automatically closed haven't been updated and re-pulled yet. Still somewhere on my never-ending to-do list.....
